- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-08f60881e2f01df0a
    zone_id: Z00303221M2EO78HUMVX6
    domain_name: heman.icu
    instances:
    - mongodb
  
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      image_id: "{{ ami_id }}"
      security_groups: "{{ sg_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: create r53 record
    amazon.aws.route53:
      state: present
      zone: "{{ zone_id }}"
      record: "{{ item.item }}.{{ domain_name }}"
      type: A 
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"

  - name: create r53 record
    amazon.aws.route53:
      state: present
      zone: "{{ zone_id }}"
      record: "{{ domain_name }}"
      type: A 
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_output.results }}"