- name: setup frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: disable default nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable nginx 1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: remove frontend html
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
    
  - name: download frontend application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: create frontend html
    ansible.builtin.file:
      path: /usr/share/nginx/html 
      state: directory

  - name: unzip frontend application
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes 
  
  - name: delete nginx conf
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent
  
  - name: copy frontend 
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: start enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes 
